# -*- coding: utf-8 -*-
"""generate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16r3RGZnV4Nuqmw9BfOng3jNoSJmbJWVP
"""

import random

from huggingface_hub import snapshot_download
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

model = 'model-name here'

def generate(model, i, dict):
  generated_statements = set()
  HF_MODEL = 'model'
  HF_MODEL_PATH = HF_MODEL.split('/')[1]


  snapshot_download(HF_MODEL, local_dir=HF_MODEL_PATH)


  tokenizer = AutoTokenizer.from_pretrained(HF_MODEL_PATH, legacy=False)
  model = AutoModelForSeq2SeqLM.from_pretrained(HF_MODEL_PATH)
  pipeline = pipeline('text2text-generation', model=model, tokenizer=tokenizer, max_new_tokens=2048)
  for _ in range(i):
    choice = random_choice(dict)
    result = pipeline('Please generate a statement of the form [x] will [y], where the statement does not need to be rational, but it must use exactly once the word will. The topic of the statement must be:' + choice)
    generated_statements.add(result)


  return generated_statements