# -*- coding: utf-8 -*-
"""various_checkers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZKJEPw46mhXvlPqoy91PI1DEPWg-ADl
"""

import negation_checker
from negation_checker import ask, neg

def checker1(statement, model):
  p = ask(statement, model)
  q = ask (statement+" and "+statement)
  return (p==q)

def checker2(statement, model):
  p = ask(statement+" and "+neg(statement))
  return (p==0)