AWS_ACCESS_KEY = ""
AWS_SECRET_KEY = ""

METACULUS_KEY = ""
MANIFOLD_KEY = ""
POLYMARKET_KEY = ""
CRYPTO_PRIVATE_KEY = ""
EMAIL = ""
GJOPEN_CSET_PASSWORD = ""


NEWSCASTCHER_KEY = "OKHYdM7QKDnuMGULpd0-lUw52pXQE4PyTPWxE_gW3r0"

OPENAI_KEY = "sk-proj-7SK4y2cpdSrAWdvyOEd5T3BlbkFJUleTv7Dy5elaMzcWKh9R"
ANTHROPIC_KEY = "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"
TOGETHER_KEY = "56b447ee5e333b3eba277ed650829149bcd8df9b953d8aa42daa0dc0bd6eb9ad"
GOOGLE_AI_KEY = ""
HF_ACCESS_TOKEN = ""

keys = {
    "AWS_ACCESS_KEY": AWS_ACCESS_KEY,
    "AWS_SECRET_KEY": AWS_SECRET_KEY,

    "METACULUS_KEY": METACULUS_KEY,
    "MANIFOLD_KEY": MANIFOLD_KEY,
    "POLYMARKET_KEY": POLYMARKET_KEY,
    "CRYPTO_PRIVATE_KEY": CRYPTO_PRIVATE_KEY,
    "EMAIL": EMAIL,
    "GJOPEN_CSET_PASSWORD": GJOPEN_CSET_PASSWORD,

    "NEWSCASTCHER_KEY": NEWSCASTCHER_KEY,

    "OPENAI_KEY": OPENAI_KEY,
    "ANTHROPIC_KEY": ANTHROPIC_KEY,
    "TOGETHER_KEY": TOGETHER_KEY,
    "GOOGLE_AI_KEY": GOOGLE_AI_KEY,
    "HF_ACCESS_TOKEN": HF_ACCESS_TOKEN,
}
