import os
from dotenv import load_dotenv

load_dotenv()

AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_KEY = os.getenv("AWS_SECRET_KEY")

METACULUS_KEY = os.getenv("METACULUS_KEY")
MANIFOLD_KEY = os.getenv("MANIFOLD_KEY")
POLYMARKET_KEY = os.getenv("POLYMARKET_KEY")
CRYPTO_PRIVATE_KEY = os.getenv("CRYPTO_PRIVATE_KEY")
EMAIL = os.getenv("EMAIL")
GJOPEN_CSET_PASSWORD = os.getenv("GJOPEN_CSET_PASSWORD")

OPENAI_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_KEY = os.getenv("ANTHROPIC_KEY")
TOGETHER_KEY = os.getenv("TOGETHER_KEY")
GOOGLE_AI_KEY = os.getenv("GOOGLE_AI_KEY")
HF_ACCESS_TOKEN = os.getenv("HF_ACCESS_TOKEN")

NEWSCATCHER_KEY = os.getenv("NEWSCATCHER_KEY")

keys = {
    "AWS_ACCESS_KEY": AWS_ACCESS_KEY,
    "AWS_SECRET_KEY": AWS_SECRET_KEY,
    "METACULUS_KEY": METACULUS_KEY,
    "MANIFOLD_KEY": MANIFOLD_KEY,
    "POLYMARKET_KEY": POLYMARKET_KEY,
    "CRYPTO_PRIVATE_KEY": CRYPTO_PRIVATE_KEY,
    "EMAIL": EMAIL,
    "GJOPEN_CSET_PASSWORD": GJOPEN_CSET_PASSWORD,
    "NEWSCATCHER_KEY": NEWSCATCHER_KEY,
    "OPENAI_KEY": OPENAI_KEY,
    "ANTHROPIC_KEY": ANTHROPIC_KEY,
    "TOGETHER_KEY": TOGETHER_KEY,
    "GOOGLE_AI_KEY": GOOGLE_AI_KEY,
    "HF_ACCESS_TOKEN": HF_ACCESS_TOKEN,
}
