# ground_truth_directories=(
#     "src/data/forecasts/ConsistentForecaster_4xEE1_20240701_20240831"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_20240701_20240831_3x"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_20240701_20240831_2x"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_20240701_20240831_1x"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_20240701_20240831_0x"
#     "src/data/forecasts/ConsistentForecaster_N4_20240701_20240831"
#     "src/data/forecasts/ConsistentForecaster_N4_20240701_20240831_3"
#     "src/data/forecasts/ConsistentForecaster_N4_20240701_20240831_2"
#     "src/data/forecasts/ConsistentForecaster_N4_20240701_20240831_1"
#     "src/data/forecasts/ConsistentForecaster_N4_20240701_20240831_0"
#     "src/data/forecasts/ConsistentForecaster_P4_20240701_20240831"
#     "src/data/forecasts/ConsistentForecaster_P4_20240701_20240831_3"
#     "src/data/forecasts/ConsistentForecaster_P4_20240701_20240831_2"
#     "src/data/forecasts/ConsistentForecaster_P4_20240701_20240831_1"
#     "src/data/forecasts/ConsistentForecaster_P4_20240701_20240831_0"
#     "src/data/forecasts/ConsistentForecaster_NP4_20240701_20240831"
#     "src/data/forecasts/ConsistentForecaster_NP4_20240701_20240831_3"
#     "src/data/forecasts/ConsistentForecaster_NP4_20240701_20240831_2"
#     "src/data/forecasts/ConsistentForecaster_NP4_20240701_20240831_1"
#     "src/data/forecasts/ConsistentForecaster_NP4_20240701_20240831_0"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_scraped"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_scraped_3x"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_scraped_2x"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_scraped_1x"
#     "src/data/forecasts/ConsistentForecaster_4xEE1_scraped_0x"
#     "src/data/forecasts/ConsistentForecaster_N4_scraped"
#     "src/data/forecasts/ConsistentForecaster_N4_scraped_3"
#     "src/data/forecasts/ConsistentForecaster_N4_scraped_2"
#     "src/data/forecasts/ConsistentForecaster_N4_scraped_1"
#     "src/data/forecasts/ConsistentForecaster_N4_scraped_0"
#     "src/data/forecasts/ConsistentForecaster_P4_scraped"
#     "src/data/forecasts/ConsistentForecaster_P4_scraped_3"
#     "src/data/forecasts/ConsistentForecaster_P4_scraped_2"
#     "src/data/forecasts/ConsistentForecaster_P4_scraped_1"
#     "src/data/forecasts/ConsistentForecaster_P4_scraped_0"
#     "src/data/forecasts/ConsistentForecaster_NP4_scraped"
#     "src/data/forecasts/ConsistentForecaster_NP4_scraped_3"
#     "src/data/forecasts/ConsistentForecaster_NP4_scraped_2"
#     "src/data/forecasts/ConsistentForecaster_NP4_scraped_1"
#     "src/data/forecasts/ConsistentForecaster_NP4_scraped_0"
# )
evaluation_directories=(
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_newsapi"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_newsapi_3x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_newsapi_2x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_newsapi_1x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_newsapi_0x"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_newsapi"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_newsapi_3"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_newsapi_2"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_newsapi_1"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_newsapi_0"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_newsapi"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_newsapi_3"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_newsapi_2"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_newsapi_1" #
    "src/data/forecasts/ConsistentForecaster_P4_tuples_newsapi_0"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_newsapi"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_newsapi_3"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_newsapi_2"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_newsapi_1"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_newsapi_0"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_scraped"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_scraped_3x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_scraped_2x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_scraped_1x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_scraped_0x"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_scraped"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_scraped_3"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_scraped_2"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_scraped_1"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_scraped_0"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_scraped"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_scraped_3"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_scraped_2"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_scraped_1"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_scraped_0"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_scraped"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_scraped_3"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_scraped_2"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_scraped_1"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_scraped_0"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_synthetic"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_synthetic_3x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_synthetic_2x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_synthetic_1x"
    "src/data/forecasts/ConsistentForecaster_4xEE1_tuples_synthetic_0x"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_synthetic"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_synthetic_3"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_synthetic_2"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_synthetic_1"
    "src/data/forecasts/ConsistentForecaster_N4_tuples_synthetic_0"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_synthetic"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_synthetic_3"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_synthetic_2"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_synthetic_1"
    "src/data/forecasts/ConsistentForecaster_P4_tuples_synthetic_0"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_synthetic"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_synthetic_3"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_synthetic_2"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_synthetic_1"
    "src/data/forecasts/ConsistentForecaster_NP4_tuples_synthetic_0"
)

# for DIR in "${ground_truth_directories[@]}"; do
#     python src/ground_truth_run.py --load_dir "$DIR"
# done

for DIR in "${evaluation_directories[@]}"; do
    python src/evaluation.py --load_dir "$DIR" -k all
done