###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import List, Optional, Union

from . import types

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class GenerateQuestionInput(BaseModel):
    
    
    example_questions: List["SyntheticQuestion"]
    category: Optional[str] = None
    tags: List[Optional[str]]

class QuestionGenerationResponse3(BaseModel):
    
    
    question_1: Optional["SyntheticQuestion"] = None
    question_2: Optional["SyntheticQuestion"] = None
    question_3: Optional["SyntheticQuestion"] = None

class SyntheticQuestion(BaseModel):
    
    
    title: Optional[str] = None
    category: Optional[str] = None
    tags: Optional[str] = None
    feedback: Optional[str] = None
    fixed: Optional[bool] = None
