###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import List, Optional, Union


class GenerateQuestionInput(BaseModel):
    
    
    example_questions: List["SyntheticQuestion"]
    category: str
    tags: List[str]

class QuestionGenerationResponse3(BaseModel):
    
    
    question_1: "SyntheticQuestion"
    question_2: "SyntheticQuestion"
    question_3: "SyntheticQuestion"

class SyntheticQuestion(BaseModel):
    
    
    title: str
    category: str
    tags: str
    feedback: Optional[str] = None
    fixed: Optional[bool] = None
